---
title: "Figure A"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gutenbergr)
```

This column plot explores the prevalence of bookshelf inclusion. A book can belong to one or (counter-intuitively) several bookshelves, but the most common case is the book being absent from any bookshelf.

```{r data prep}
bookshelf_multiplicity_summary <- gutenberg_metadata %>%
  filter(language == 'en', rights == "Public domain in the USA.", has_text) %>%
  mutate(bookshelves = str_count(gutenberg_bookshelf, pattern = "/") + 1) %>%
  mutate(bookshelves = replace_na(bookshelves, 0)) %>%
  group_by(bookshelves) %>%
  summarise(count = n()) %>%
  mutate(bookshelves = as.character(bookshelves))
```

```{r display plot}
ggplot(bookshelf_multiplicity_summary, aes(x = bookshelves, y = count, fill = bookshelves)) +
  geom_col() +
  scale_fill_viridis_d(direction = -1, begin = 0.1) +
  labs(x = NULL, y = "Number of eBooks", fill = "Number of assigned bookshelves")
```